- config:
    name: pc撤单case
    base_url: ${base_url()}
    variables:
        #pc新建订单需要的相关数据
        L1: ['1','5']
        L2: ['黑','B']
        L3: []

        #pc新建订单需要的相关数据
        L1: ['1','5']
        L2: ['黑','B']
        L3: []
        caseNo: ${random_Num(9)}
        ownerPhone: ${random_Num(9, $L1)} #车主手机号
        carNo: ${random_Num(6, $L2)}
        injuredPhone: '13200780881' #pc维护的伤者电话

        visitorPhone: '15112313347'  #探视员手机号
        visitorSignature: '小小点'  #探视员签名
        injuredSignature: '伤者的名字'  #伤者签名

        birthday: 50653440000  #1986-01-20
        phone: '18681461457'  #h5维护的伤者电话
        beginDate: 1555344000000 #2019-04-16
        endDate: 1556035200000  #2019-04-24
        hospitalizedDate: 1557676800000 #2019-05-13
        leaveDate: 1557763200000  #2019-05-14
        accTime: '1554694924000'

- test:
    name: 前置条件-pc新建订单
    testcase: testcases/modulecase/module_addOrder_h5Login.yaml
    output:
        - pc_token
        - orderId

- test:
    name: 正常查看
    api: api/pc/cancel.yaml
    validate:
        - eq: [status_code, 200]
        - eq: [content.code, 200]
        - eq: [content.message, '处理成功']
        - eq: [content.status, 'success']

- test:
    name: 异常场景_订单号为空撤单
    api: api/pc/cancel.yaml
    variables:
        orderId: ''
    validate:
        - eq: [status_code, 200]
        - eq: [content.code, 503]
        - eq: [content.message, '退单失败']
        - eq: [content.status, 'error']

- test:
    name: 异常场景_撤单原因为空的订单  -- 有bug
    api: api/pc/cancel.yaml
    variables:
        reason: ''
    validate:
        - eq: [status_code, 200]
        - eq: [content.code, 503]
        - eq: [content.message, '退单失败']
        - eq: [content.status, 'error']

- test:
    name: 异常场景_订单和撤单原因都为空
    api: api/pc/cancel.yaml
    variables:
        orderId: ''
        reason: ''
    validate:
        - eq: [status_code, 200]
        - eq: [content.code, 503]
        - eq: [content.message, '退单失败']
        - eq: [content.status, 'error']

